import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View, Button, Image, Dimensions, ScrollView, TouchableOpacity, Linking} from 'react-native';


class About extends Component{

    static navigationOptions = ({ navigation }) => {
        return{
            headerRight: (
            <Button
                color='#c80512'
                onPress={() => navigation.push('RandomNumber') }
                title="QRNG"
                />
            ),
            headerLeft :(
            <Button
                color='#c80512'
                onPress={() => navigation.push('MegaMillion') }
                title="Mega Million"
                />
            )
        }

    };


    openExternalLinks = (url) => {
      Linking.openURL(url).catch(err => console.error('An error occurred', err));
    }

    render() {
        return (
          <ScrollView style={styles.bg}>
            <View style={styles.addMargin}>
              <Text style={styles.welcome}>
              The RNG & games are built upon the raw and true random numbers from inherently stochastic quantum processes. Our QRNs pass all randomness tests of the NIST and Dieharder test suites without any randomness extraction.</Text>
              <View style={styles.welcome}>
              <Text style={styles.welcomeWithNoMarginBottom}>
              To learn more about how our QRNs and other ongoing quantum R&D, please feel free to contact Prof. Yuping Huang
              </Text>
              <TouchableOpacity onPress={() => this.openExternalLinks('mailto:yuping.huang@stevens.edu')}>
                <Text style={styles.link}>yuping.huang@stevens.edu</Text>
              </TouchableOpacity>
              </View>
              <View style={styles.welcome}>
              <Text style={styles.welcomeWithNoMarginBottom}>
              Programmable quantum random number generator without postprocessing
              </Text>

              <TouchableOpacity onPress={() => this.openExternalLinks('https://www.osapublishing.org/ol/abstract.cfm?uri=ol-43-4-631')}>
                <Text style={styles.link}>(https://www.osapublishing.org/ol/abstract.cfm?uri=ol-43-4-631)</Text>
              </TouchableOpacity>
              </View>
              <View style={styles.welcome}>
                <Text style={styles.welcomeWithNoMarginBottom}>Quantum Systems for Monte Carlo Methods and Applications to Fractional Stochastic Processes </Text>

                <TouchableOpacity onPress={() => this.openExternalLinks('https://arxiv.org/abs/1810.05639')}>
                  <Text style={styles.link}>(https://arxiv.org/abs/1810.05639)</Text>
                </TouchableOpacity>
                </View>
              <Text style={styles.welcome}>
              The QRNs are generated by Laboratory for Quantum Enhanced Systems & Technology (QuEST), where this mobile app is developed with Siddharth Choudhary, Stevens Institute of Technology, Hoboken, NJ, U.S.A.
              </Text>

              <View style={styles.row}>
                <Image source={require('../Images/quest.png')} style={styles.imageDimensions} />
                <Image source={require('../Images/stevens_logo.png')} style={[styles.imageDimensions, styles.ml20]} />
              </View>
            </View>

          </ScrollView>
        );
      }
}

const styles = StyleSheet.create({
    welcome: {
      fontSize: 16,
      color : '#c80512',
      marginBottom : 20
    },
    welcomeWithNoMarginBottom:{
      fontSize:16,
      color: '#c80512',
    },
    imageDimensions :{
      width : 150,
      height : 50,
      resizeMode:'contain'
    },
    row :{
      flex : 1,
      flexDirection : 'row'
    },
    ml20 : {
      marginLeft : 20
    },
    bg :{
      margin : 0,
      backgroundColor : '#fff'
    },
    addMargin :{
      margin : 20,
    },
    link :{
      color : 'blue',
    }

  });


export default About;
